#!/bin/bash

RUN_DIR=/var/vcap/sys/run/traefik
LOG_DIR=/var/vcap/sys/log/traefik
CONFIG=/var/vcap/jobs/traefik/config/traefik.toml
PIDFILE=${RUN_DIR}/pid

case $1 in

  start)
    mkdir -p $RUN_DIR $LOG_DIR
    chown -R vcap:vcap $RUN_DIR $LOG_DIR

    echo $$ > $PIDFILE

    test -f "${CONFIG}"

    /var/vcap/jobs/traefik/bin/set_consul_kv \
      1>>${LOG_DIR}/consul_set_kv.stdout.log \
      2>>${LOG_DIR}/consul_set_kv.stderr.log

    exec chpst /var/vcap/packages/traefik/bin/traefik \
      -c "${CONFIG}" \
      1>>${LOG_DIR}/traefik.stdout.log \
      2>>${LOG_DIR}/traefik.stderr.log
    ;;

  stop)
    kill -9 "$(cat $PIDFILE)"
    rm -f $PIDFILE

    ;;

  *)
    echo "Usage: ctl {start|stop}" ;;

esac
